### ISSUE TITLE
getBidsRun and getIncremental do not use correct events, README, or dataset_description

### ISSUE THREAD

**Issue by spolcyn** [brainiak/rt-cloud#22]
A valid BIDS archive will have all of these files, and they should be included within an Incremental obtained via `getIncremental` from a BIDS Run (and thus a BIDS Run obtained using `getBidsRun` should also have these values).

Methods to add to BIDS Archive to help support this:
`getDatasetMetadata`
`getReadme`
`getEvents`

**Comment by gdoubleyew** [comment]
Hi Stephen,
I think this change is in the code now. If you have a moment, could you verify?

**Comment by spolcyn** [comment]
Yep, it looks like #58 fixes this.
