### ISSUE TITLE
Create BIDS-Incremental pipeline example

### ISSUE THREAD

**Issue by spolcyn** [brainiak/rt-cloud#53]
Having an streaming example that passes data through the BIDS pipeline, creates BIDS Archives, does basic analysis, and passes the data back to verify the analyses match would be useful both for future users to base their own projects on and for testing purposes to verify correctness.

**Comment by PaulScotti** [comment]
Template project (https://github.com/brainiak/rtcloud-projects/tree/main/template) uses BIDS Incrementals & BIDS Archives and is referenced in the Readme
