### ISSUE TITLE
Can't run OpenNeuro sample project with subject name that is a number

### ISSUE THREAD

**Issue by spolcyn** [brainiak/rt-cloud#59]
When using a `subjectName` in the toml config file like "01", the project server treats this in the config as being its number form, i.e., 1. Accordingly, a dataset with `sub-01` doesn't work, as the subject's ID is '01', not '1'. The same problem occurs when the subject's ID is just a number (e.g., '13'), which also gets converted to a number. Since the subject entity is a string, searches fail when the subject is a number. (try dataset `ds003524` to replicate)

Doing a `toml.load` on the toml file with `subjectName="01"` returns a dict that has '01' in it. Therefore, the problem doesn't seem to be in the toml module. Thus, it's possible another component (like the web interface) is manipulating the '01' into a numerical 1 at some point.

**Comment by gdoubleyew** [comment]
This is fixed in commit caecd98 01/12/2022 "OpenNeuro settings as strings"
