### ISSUE TITLE
localhost connection failed 

### ISSUE THREAD

**Issue by peetal** [brainiak/rt-cloud#70]
Hi, 

I'm having trouble opening the `http://localhost:8888` on my web browser after launching the project server by doing `scripts/run-projectInterface.sh -p [my-project] -c [my-project-configuration]`. I got the error page saying `Secure Connection Failed: An error occurred during a connection to localhost:8888. You are attempting to import a cert with the same issuer/serial as an existing cert, but that is not the same cert. Error code: SEC_RROR_REFUSED_ISSUE_AND_SERIAL`. 

I'm using Linux (Ubuntu 20.04), with the latest version of rt-cloud. Importantly, I have been using this workstation to run rt-cloud with this command for a while without encountering this problem at all. But recently, I requested a static IP address for this work station. I then removed rtcloud from local and re-cloned it. Then I followed the set up instructions to set up `certs` and `web`, after which I encountered this error when trying to launch the server. I tried to create certs with `local_ip_addr` being either the static IP or the output of `hostname -i`, but got the aforementioned error regardless. 

I have very limited understanding on how the server works and any insights would be extremely helpful! Thank you very much in advance! 

Thanks, 
Peeta

**Comment by gdoubleyew** [comment]
Hi Peeta,
I'm copying my reply from Nov. 18th here. Please indicate the current status.

========
Did you import the new certificate into your browser?
Also you will need to copy the new certificate to the certs/ directory where the scannerDataService (i.e. FileWatcher) and subjectService are running (if on a separate computer).

In this doc there are instructions on adding the SSL certificate to a browser (about 2/3 down the page) https://github.com/brainiak/rt-cloud/blob/master/docs/how-to-run.md
 
Also, when you run the projectInterface, try passing the --ip [static_ip] parameter to it, this will include it in the ssl-certificate.
 
And as an additional test, if you run the projectInterface with the --test option it will run unencrypted and so not need the SSL certificate. This is a good test to see if it is possibly some other problem that is happening.
 
Let me know what you find out. We can also have a zoom call to debug if you’d like.
